version: "3.9"

services:
  image:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        AWS_REGION: ${AWS_REGION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - .:/infra
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
