# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "maks-k-one-tf"
    dynamodb_table = "maks-k-one-lock"
    encrypt        = true
    key            = "terraform.tfstate"
    region         = "eu-west-3"
  }
}
